name = "vaultdl"
main = "worker.js"
compatibility_date = "2024-04-01"

# ── KV Namespace ──
[[kv_namespaces]]
binding = "VAULTDL_CACHE"
id = "073d838ea9034066ac3dc41131254fa8" 

# ── التنسيق الجديد للملفات الثابتة (أفضل من [site]) ──
[assets]
directory = "./"
binding = "ASSETS"